// Diese Datei enthält die Kategorien für das Spiel "Wellenlänge"
const categories = [
    "Nenne eine Porno-Kategorie",
    "Nenne eine Bestrafung in der Schule",
    "Nenne eine Ausrede, warum man seine Hausaufgaben vergessen hat",
    "Nenne einen Grund, warum man nicht für eine Prüfung gelernt hat",
    "Nenne eine Straftat/Ordnungswidrigkeit",
    "Nenne eine Ausrede, warum man zu spät zum Unterricht kommt",
    "Nenne einen Shampoo-Duft",
  "Nenne einen Fußball-Verein",
  "Nenne eine politische Partei",
  "Nenne eine Aktivität im Zug",
  "Nenne ein Produkt aus dem Zug-Boardbistro",
  "Nenne ein Duty-Free-Produkt am Flughafen",
  "Nenne einen Flughafen",
  "Nenne einen Politiker",
  "Nenne einen Bart-Stil",
  "Nenne ein Eis am Stiel",
  "Nenne eine Biermarke",
  "Nenne ein Reisziel",
  "Nenne ein Vereinswappen",
  "Nenne ein Stadtteil in München",
  "Nenne eine Cola-Marke",
  "Nenne eine Schuhmarke",
  "Nenne ein Kleidungsstück",
  "Nenne ein Küchengerät",
  "Nenne ein Land in Afrika",
  "Nenne ein Land in Asien",
  "Nenne ein Land in Nord-, Mittel- oder Südamerika",
  "Nenne eine Freizeitaktivität/-spiel als Kind",
  "Nenne eine Burger-Kette/-Laden",
  "Nenne ein NFL-Team",
  "Nenne ein NBA-Team",
  "Nenne eine politische Forderung",
  "Nenne einen Grund für eine Demo",
  "Nenne eine Aktivität im Sommer",
  "Nenne eine Aktivität im Winter",
  "Nenne ein Müsli",
  "Nenne eine Nationalität für deinen Partner/Partnerin",
  "Nenne ein Unternehmenslogo",
  "Nenne ein Land für ein Auslandsjahr",
  "Nenne eine Hundeart",
  "Nenne eine Chips-Marke",
  "Nenne einen Laden in einem Einkaufszentrum",
  "Nenne ein Alter, um den Führerschein zu machen",
  "Nenne einen Monat",
  "Nenne eine Geburtstagslocation",
  "Nenne eine Geburtstagslocation als Kind",
  "Nenne eine Frisur",
  "Nenne einen Zeitraum zwischen 2 Friseur-Besuchen",
  "Nenne einen YouTube-Kanal",
  "Nenne einen TikTok-Kanal",
  "Nenne ein Meme",
  "Nenne eine Handymarke",
  "Nenne eine Sprache zum Erlernen",
  "Nenne eine Sprache",
  "Nenne ein Schulfach",
  "Nenne ein Körperteil nach Wichtigkeit",
  "Nenne eine Fortbewegungsart",
  "Nenne ein Jugendwort",
  "Nenne einen Fußballtransfer",
  "Nenne ein Fußballstadion",
  "Nenne ein soziales Netzwerk",
  "Nenne ein Videospiel",
  "Nenne einen Sportler",
  "Nenne eine Uhrzeit zum Aufstehen",
  "Nenne einen Club zum Feiern",
  "Nenne eine Freizeitbeschäftigung",
  "Nenne einen Film/Serie",
  "Nenne eine Essenskategorie bei einem Lieferdienst",
  "Nenne ein Softdrink",
  "Nenne einen Verwandtschaftsgrad",
  "Nenne eine Urlaubsbeschäftigung",
  "Nenne eine Zeitepoche",
  "Nenne einen Promi",
  "Nenne einen Streaming-Anbieter",
  "Nenne eine Sucht",
  "Nenne einen Grund warum man einen Sportverein nicht mag",
  "Nenne eine Flugdauer",
  "Nenne eine Krankheit",
  "Nenne ein Lied",
  "Nenne ein Studiengang",
  "Nenne eine Wettertemperatur",
  "Nenne einen Supermarkt/Discounter",
  "Nenne einen Beruf",
  "Nenne eine Süßigkeit",
  "Nenne einen TV-Sender",
  "Nenne eine Person für die du schwul werden würdest",
  "Nenne einen Dialekt",
  "Nenne einen Serien-/Filmcharakter",
  "Nenne ein Frühstück",
  "Nenne eine Sportart zum anschauen",
  "Nenne eine Verschwörungstheorie",
  "Nenne eine Farbe",
  "Nenne einen Vornamen",
  "Nenne einen Ort für einen Junggesellenabschied",
  "Nenne ein Tier",
  "Nenne einen Wochentag",
  "Nenne einen Emoji",
  "Nenne einen Duft/Parfüm",
  "Nenne eine Automarke",
  "Nenne eine Band",
    "Nenne eine Eissorte",
  "Nenne ein Gesellschaftsspiel",
  "Nenne eine olympische Disziplin",
  "Nenne eine Aktivität am Wochenende",
  "Nenne eine Uhrzeit",
  "Nenne eine Blume",
  "Nenne ein Alter",
  "Nenne eine Fleischart",
  "Nenne einen Influencer",
  "Nenne eine Sehenswürdigkeit",
  "Nenne einen Ort für das erste Date",
  "Nenne einen Ort für Sex",
  "Nenne eine Dönerzutat",
  "Nenne einen Burger",
  "Nenne ein Fast-Food-Restaurant",
  "Nenne eine U-Bahn-Station",
  "Nenne eine Porno-Website",
  "Nenne eine Fanszene eines Sportvereins",
  "Nenne einen Dartspieler",
  "Nenne einen Formel-1-Fahrer",
  "Nenne eine Pizza",
  "Nenne eine Luxusmarke",
  "Nenne eine Bierart",
  "Nenne eine Fußball-Weltmeisterschaft",
  "Nenne eine Fußball-Nationalmannschaft",
  "Nenne eine Urlaubsdauer",
  "Nenne eine Musikrichtung",
  "Nenne ein deutsches Essen",
  "Nenne eine Influencer-Kategorie",
  "Nenne eine App",
  "Nenne eine Zeichentrickfilm/-serie",
  "Nenne einen Anlass zum Trinken",
  "Nenne ein Geschenk",
  "Nenne einen Fußball-Wettbewerb",
  "Nenne ein Trikot eines Sportvereins",
  "Nenne ein Gemüse",
  "Nenne ein Obst",
  "Nenne einen Austragungsort für eine Fußball-Weltmeisterschaft",
  "Nenne eine Abflugsuhrzeit",
  "Nenne eine Zugabfahrtszeit",
  "Nenne eine Fluggesellschaft",
  "Nenne ein Bundesland",
  "Nenne einen US-Bundestaat",
  "Nenne ein Gewürz",
  "Nenne einen Fetisch",
  "Nenne ein Tattoo-Motiv",
  "Nenne ein Wetter",
  "Nenne ein Glücksspiel-Art",
  "Nenne einen Sportwettenanbieter",
  "Nenne eine Vorspeise",
  "Nenne ein Dessert",
  "Nenne einen Shot",
  "Nenne eine Spirituose",
  "Nenne eine Glaubensart/-richtung",
  "Nenne eine Red Flag",
  "Nenne eine Green Flag",
  "Nenne eine Dating-App",
  "Nenne eine Anzahl an eigenen Kindern",
  "Nenne eine Form",
  "Nenne eine T-Shirt-Farbe",
  "Nenne eine Hosenfarbe",
  "Nenne ein Band für ein T-Shirt-Print",
  "Nenne einen Friends-Charakter",
  "Nenne einen How I Met Your Mother Charakter",
  "Nenne eine Wassermarke",
  "Nenne ein Tier, das im Wasser lebt",
  "Nenne ein Fabelwesen",
  "Nenne eine deutsche Komödie",
  "Nenne eine Tankstelle",
  "Nenne ein Pokémon",
  "Nenne ein Nintendo-Spiel",
  "Nenne einen Super Mario Charakter",
  "Nenne ein Super Mario Spiel",
  "Nenne einen Käse",
  "Nenne einen Kuchen",
  "Nenne eine Crêpes-Variante",
  "Nenne einen Snack im Stadion",
  "Nenne eine Rückennummer im Fußball",
  "Nenne ein Accessoire",
  "Nenne ein Fachbereich in dem man einen Doktor hat",
  "Nenne eine Facharztrichtung",
  "Nenne eine Veranstaltung",
  "Nenne eine Sportverletzung",
  "Nenne eine Farbe für einen Vorhang",
  "Nenne eine Farbe für eine Krawatte",
  "Nenne einen Ort für einen Antrag",
  "Nenne eine Pärchen-Aktivität",
  "Nenne ein Sonderzeichen",
  "Nenne ein Wappentier",
  "Nenne eine Länderflagge",
  "Nenne eine Hauptstadt",
  "Nenne eine sexuelle Orientierung",
  "Nenne eine Schulklasse",
  "Nenne ein Filmgenre",
  "Nenne eine Oscar-Kategorie",
  "Nenne ein Lied zum Joggen",
  "Nenne ein Lied zum Autofahren",
  "Nenne etwas, das man kurz vorm Schlafen gehen macht/nimmt",
  "Nenne eine Sportmarke",
  "Nenne eine Wohnungsdeko",
  "Nenne eine Schlafzimmer-Deko",
  "Nenne eine deutsche Stadt",
  "Nenne ein Land für einen Strandbesuch",
  "Nenne eine Mische für Wodka",
  "Nenne eine Mische für Gin",
  "Nenne eine Mische für Rum",
  "Nenne ein Kinosnack",
  "Nenne einen deutschen Film/Serie",
  "Nenne eine Uhrzeit, um mit Daydrinking anzufangen",
  "Nenne eine Uhrzeit, um vorzuglühen",
  "Nenne eine Uhrzeit, um ins Büro zu gehen",
  "Nenne einen männlichen Vornamen",
  "Nenne einen weiblichen Vornamen",
  "Nenne eine Karte aus einem bayrischen Kartendeck",
  "Nenne einen Spongebob Schwammkopf Charakter",
  "Nenne eine Chat-Abkürzung",
  "Nenne eine Uhrzeit zum Schlafen gehen",
  "Nenne einen Die Simpsons Charakter",
  "Nenne mir eine Geschwindigkeit mit dem Auto",
  "Nenne eine Aktivität im Olympiapark",
  "Nenne eine Uhrzeit, um sich mit Freunden zu treffen",
  "Nenne einen Wochentag, um etwas mit seinen Eltern zu machen",
  "Nenne eine Sauce",
  "Nenne ein Tier auf dem man reiten kann",
  "Nenne einen Schauspieler",
  "Nenne ein Trinkspiel",
  "Nenne einen Moment für ein Bier (Feierabend, nach dem Sport, Stadion,etc.)"
];
