// Diese Datei enthält die Kategorien für das Spiel "Wellenlänge"
const categories = [
    "Nenne eine Porno-Kategorie",
  "Nenne einen Fußball-Verein",
  "Nenne eine politische Partei",
  "Nenne einen Politiker",
  "Nenne eine Biermarke",
  "Nenne ein Reisziel",
  "Nenne ein Vereinswappen",
  "Nenne ein Schulfach",
  "Nenne ein Körperteil nach Wichtigkeit",
  "Nenne eine Fortbewegungsart",
  "Nenne ein Jugendwort",
  "Nenne einen Fußballtransfer",
  "Nenne ein Fußballstadion",
  "Nenne ein soziales Netzwerk",
  "Nenne ein Videospiel",
  "Nenne einen Sportler",
  "Nenne eine Uhrzeit zum Aufstehen",
  "Nenne einen Club zum Feiern",
  "Nenne eine Freizeitbeschäftigung",
  "Nenne einen Film/Serie",
  "Nenne eine Essenskategorie bei einem Lieferdienst",
  "Nenne ein Softdrink",
  "Nenne einen Verwandtschaftsgrad",
  "Nenne eine Urlaubsbeschäftigung",
  "Nenne eine Zeitepoche",
  "Nenne einen Promi",
  "Nenne einen Streaming-Anbieter",
  "Nenne eine Sucht",
  "Nenne einen Grund warum man einen Sportverein nicht mag",
  "Nenne eine Flugdauer",
  "Nenne eine Krankheit",
  "Nenne ein Lied",
  "Nenne ein Studiengang",
  "Nenne eine Wettertemperatur",
  "Nenne einen Supermarkt/Discounter",
  "Nenne einen Beruf",
  "Nenne eine Süßigkeit",
  "Nenne einen TV-Sender",
  "Nenne eine Person für die du schwul werden würdest",
  "Nenne einen Dialekt",
  "Nenne einen Serien-/Filmcharakter",
  "Nenne ein Frühstück",
  "Nenne eine Sportart zum anschauen",
  "Nenne eine Verschwörungstheorie",
  "Nenne eine Farbe",
  "Nenne einen Vornamen",
  "Nenne einen Ort für einen Junggesellenabschied",
  "Nenne ein Tier",
  "Nenne einen Wochentag",
  "Nenne einen Emoji",
  "Nenne einen Duft/Parfüm",
  "Nenne eine Automarke",
  "Nenne eine Band",
    "Nenne eine Eissorte",
  "Nenne ein Gesellschaftsspiel",
  "Nenne eine olympische Disziplin",
  "Nenne eine Aktivität am Wochenende",
  "Nenne eine Uhrzeit",
  "Nenne eine Blume",
  "Nenne ein Alter",
  "Nenne eine Fleischart",
  "Nenne einen Influencer",
  "Nenne eine Sehenswürdigkeit",
  "Nenne einen Ort für das erste Date",
  "Nenne einen Ort für Sex",
  "Nenne eine Dönerzutat",
  "Nenne einen Burger",
  "Nenne ein Fast-Food-Restaurant",
  "Nenne eine U-Bahn-Station",
  "Nenne eine Porno-Website",
  "Nenne eine Fanszene eines Sportvereins",
  "Nenne einen Dartspieler",
  "Nenne einen Formel-1-Fahrer",
  "Nenne eine Pizza",
  "Nenne eine Luxusmarke",
  "Nenne eine Bierart",
  "Nenne eine Fußball-Weltmeisterschaft",
  "Nenne eine Fußball-Nationalmannschaft",
  "Nenne eine Urlaubsdauer",
  "Nenne eine Musikrichtung",
  "Nenne ein deutsches Essen",
  "Nenne eine Influencer-Kategorie",
  "Nenne eine App",
  "Nenne eine Zeichentrickfilm/-serie",
  "Nenne einen Anlass zum Trinken",
  "Nenne ein Geschenk",
  "Nenne einen Fußball-Wettbewerb",
  "Nenne ein Trikot eines Sportvereins",
  "Nenne ein Gemüse",
  "Nenne ein Obst",
  "Nenne einen Austragungsort für eine Fußball-Weltmeisterschaft",
  "Nenne eine Abflugsuhrzeit",
  "Nenne eine Zugabfahrtszeit",
  "Nenne eine Fluggesellschaft",
  "Nenne ein Bundesland",
  "Nenne einen US-Bundestaat",
  "Nenne ein Gewürz",
  "Nenne einen Fetisch",
  "Nenne eine Soße für Pommes",
  "Nenne ein Tier auf dem man reiten kann",
  "Nenne einen Schauspieler",
  "Nenne ein Trinkspiel",
  "Nenne einen Moment für ein Bier (Feierabend, nach dem Sport, Stadion,etc.)"
];
